### ISSUE TITLE
怎么使用？直接拷贝？

### ISSUE THREAD

**Issue by lyjshadowking** [wuhenzhizao/android-titlebar#1]
作者你好！我偶然间发现这个标题栏，感觉非常好用，感谢您开源出这个东西。但是我阅读了readme，发现您并没有提供使用方式，例如gradle的compile。请问这是直接下载源码拷贝？我感觉这是比较麻烦的，还希望作者能够明确给出使用方式。再次万分感谢！

**Comment by wuhenzhizao** [comment]
你好，你指的compile是远程maven仓的依赖吧，暂时没有提供。也可以把代码下载下来，将library这个module导进您的工程，作为本地依赖。当然我觉得直接拷贝进去就行。
如果您项目中标题栏的样式和默认的差别不大，可以在xml里直接配置，大部分样式都可以通过配置修改。如果有更多的要求，可以自己修改源码，注释都比较清晰。
可以的话，帮忙加一下星吧

**Comment by zhangchaoxu** [comment]
用jitpack.io吧。我生成了一个

```
allprojects {
		repositories {
			...
			maven { url 'https://jitpack.io' }
		}
	}

	dependencies {
	        compile 'com.github.wuhenzhizao:android-titlebar:-SNAPSHOT'
	}
```

**Comment by wuhenzhizao** [comment]
已经添加jcenter依赖，README已更新，感谢 @zhangchaoxu
