### ISSUE TITLE
希望提供更多 使用java代码设置的接口

### ISSUE THREAD

**Issue by tdxtxt** [wuhenzhizao/android-titlebar#10]

**Comment by mmdet** [comment]
不是可以获取到各个view？获取到view，不就可以使用java代码进行设置与更改了

**Comment by wuhenzhizao** [comment]
仅仅增加更多设置的接口，接口数量多，不便于理解和维护，所以直接向外暴露了视图，想怎么改，自己去设置

**Comment by tdxtxt** [comment]
这个确实很方便，但是如果可以动态的设置rightType，centerType，leftType，我觉得就很完美了，因为界面布局代码中include一个统一head布局，然后代码控制左中右的布局类型。
