### ISSUE TITLE
状态栏文字颜色怎么更改

### ISSUE THREAD

**Issue by 617450941** [wuhenzhizao/android-titlebar#11]
状态栏文字颜色怎么更改 没找到这个api

**Comment by wuhenzhizao** [comment]
xml中可以配置，titlebar:centerTextColor
代码中，可以调用getCenterTextView获取到TextView，自己修改

**Comment by 617450941** [comment]
![image](https://user-images.githubusercontent.com/7607957/41143369-968b27c2-6b2b-11e8-9477-b42550bd7f5c.png)
状态栏还是黑色的

**Comment by wuhenzhizao** [comment]
你自己修改了标题栏的颜色，仔细检查

**Comment by 617450941** [comment]
不是标题栏 是指上面的状态栏

**Comment by 617450941** [comment]
![image](https://user-images.githubusercontent.com/7607957/41143701-d801c35e-6b2c-11e8-8298-aee0736cfe57.png)
是指这里的颜色

**Comment by 617450941** [comment]
调用了centerTextColor 只改了标题栏的颜色 上面的状态栏颜色没生效

**Comment by wuhenzhizao** [comment]
看文档， titlebar:titleBarColor="color"             // 标题栏背景颜色

**Comment by 617450941** [comment]
我是说状态栏的文字颜色 不是背景颜色

**Comment by zhouhuirun2015** [comment]
我也没找到能修改状态栏文字颜色的属性
