### ISSUE TITLE
compileOptions 能否对JAVA7做兼容

### ISSUE THREAD

**Issue by katohawk** [wuhenzhizao/android-titlebar#14]
compileOptions {
        sourceCompatibility 1.8
        targetCompatibility 1.8
    }
是否多余,能否对低版本兼容,去掉他

**Comment by wuhenzhizao** [comment]
是碰到了编译问题？

**Comment by katohawk** [comment]
嗯 是的 现在还有很多项目是没有启用JAVA8的

**Comment by wuhenzhizao** [comment]
ok，我会尽快更新版本
