### ISSUE TITLE
布局中存在EditText 输入法无法自动弹出

### ISSUE THREAD

**Issue by Liberations** [wuhenzhizao/android-titlebar#19]
布局中存在EditText 输入法无法自动弹出 CommonTitleBar获取了焦点？

**Comment by wuhenzhizao** [comment]
标题栏包含了搜索框吗

**Comment by wuhenzhizao** [comment]
如果标题栏不包含搜索框，应该和CommonTitleBar没多大关系，可以去掉CommonTitleBar验证一下

**Comment by Liberations** [comment]
没有 注释CommonTitleBar 即可正常获取焦点，贴上代码吧。
 `<?xml version="1.0" encoding="utf-8"?>
<RelativeLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:titlebar="http://schemas.android.com/apk/res-auto"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:background="@color/white"
    android:fitsSystemWindows="true"
    android:orientation="vertical">

   

    <com.zhiguan.rebate.business.widget.ClearEditText
        android:id="@+id/et_phone_activity_bind_phone"
        android:layout_width="match_parent"
        android:layout_height="50dp"
        android:layout_marginLeft="12dp"
        android:layout_marginRight="12dp"
        android:layout_marginTop="30dp"
        android:background="@drawable/shape_login"
        android:drawableLeft="@drawable/ic_phone"
        android:drawablePadding="15dp"
        android:focusable="true"
        android:focusableInTouchMode="true"
        android:gravity="center_vertical"
        android:hint="@string/label_mobile"
        android:inputType="phone"
        android:maxLength="11"
        android:paddingLeft="15dp"
        android:paddingRight="15dp"
        android:singleLine="true"
        android:textColorHint="#999999"
        android:textSize="14sp" />

    <LinearLayout
        android:id="@+id/ll_send_code_activity_bind_phone"
        android:layout_width="match_parent"
        android:layout_height="50dp"
        android:layout_below="@+id/et_phone_activity_bind_phone"
        android:layout_marginLeft="12dp"
        android:layout_marginRight="12dp"
        android:layout_marginTop="22dp"
        android:background="@drawable/shape_login"
        android:gravity="center_vertical"
        android:orientation="horizontal">

        <EditText
            android:id="@+id/et_code_activity_bind_phone"
            android:layout_width="match_parent"
            android:layout_height="50dp"
            android:layout_weight="1"
            android:background="#f8f8f8"
            android:drawableLeft="@drawable/ic_code"
            android:drawablePadding="15dp"
            android:gravity="center_vertical"
            android:hint="@string/label_code"
            android:inputType="number"
            android:maxLength="6"
            android:paddingLeft="15dp"
            android:paddingRight="15dp"
            android:singleLine="true"
            android:textColorHint="#999999"
            android:textSize="14sp" />

        <Button
            android:id="@+id/btn_send_code_activity_bind_phone"
            android:layout_width="120dp"
            android:layout_height="39dp"
            android:layout_marginRight="5dp"
            android:background="@drawable/selector_code"
            android:gravity="center"
            android:text="@string/label_get_code"
            android:textColor="@drawable/selector_code_text"
            android:textSize="14sp" />
    </LinearLayout>

    <TextView
        android:id="@+id/tv_line_activity_bind_phone"
        android:layout_width="match_parent"
        android:layout_height="1px"
        android:layout_below="@+id/ll_send_code_activity_bind_phone"
        android:layout_marginLeft="12dp"
        android:layout_marginRight="12dp"
        android:layout_marginTop="15dp"
        android:background="#e5e5e5" />

    <LinearLayout
        android:id="@+id/ll_code_activity_bind_phone"
        android:layout_width="match_parent"
        android:layout_height="50dp"
        android:layout_below="@+id/tv_line_activity_bind_phone"
        android:layout_marginLeft="12dp"
        android:layout_marginRight="12dp"
        android:layout_marginTop="15dp"
        android:background="@drawable/shape_login"
        android:gravity="center_vertical"
        android:orientation="horizontal">

        <ImageView
            android:id="@+id/iv_qr_activity_bind_phone"
            android:layout_width="50dp"
            android:layout_height="match_parent"
            android:scaleType="centerInside"
            android:src="@drawable/ic_invite_code" />

        <EditText
            android:id="@+id/et_invite_activity_bind_phone"
            android:layout_width="0dp"
            android:layout_height="match_parent"
            android:layout_weight="1"
            android:background="#f8f8f8"
            android:hint="@string/label_code_tip"
            android:maxLength="11"
            android:paddingLeft="15dp"
            android:paddingRight="15dp"
            android:singleLine="true"
            android:textColor="#111111"
            android:textColorHint="#999999"
            android:textSize="14sp" />
    </LinearLayout>

    <RelativeLayout
        android:id="@+id/rl_user_activity_bind_phone"
        android:layout_width="match_parent"
        android:layout_height="50dp"
        android:layout_below="@+id/ll_code_activity_bind_phone"
        android:layout_marginLeft="12dp"
        android:layout_marginRight="12dp"
        android:layout_marginTop="15dp"
        android:gravity="center_vertical">

        <ImageView
            android:id="@+id/iv_head_invite"
            android:layout_width="50dp"
            android:layout_height="match_parent"
            android:layout_marginRight="10dp"
            android:scaleType="centerInside"
            android:src="@drawable/ic_head" />

        <TextView
            android:id="@+id/tv_tip_invite"
            android:layout_width="wrap_content"
            android:layout_height="17dp"
            android:layout_toRightOf="@+id/iv_head_invite"
            android:gravity="center_vertical"
            android:text="@string/label_invite_tip"
            android:textColor="#666666"
            android:textSize="12sp" />

        <TextView
            android:id="@+id/tv_name_activity_invite"
            android:layout_width="wrap_content"
            android:layout_height="38dp"
            android:layout_below="@+id/tv_tip_invite"
            android:layout_toRightOf="@+id/iv_head_invite"
            android:ellipsize="end"
            android:gravity="center_vertical"
            android:singleLine="true"
            android:text="@string/label_invite_tip"
            android:textColor="#111111"
            android:textSize="12sp" />

        <TextView
            android:layout_width="match_parent"
            android:layout_height="1px"
            android:layout_alignParentBottom="true"
            android:background="#e5e5e5" />
    </RelativeLayout>

    <Button
        android:id="@+id/btn_login_activity_bind_phone"
        android:layout_width="match_parent"
        android:layout_height="50dp"
        android:layout_below="@+id/ll_code_activity_bind_phone"
        android:layout_marginLeft="12dp"
        android:layout_marginRight="12dp"
        android:layout_marginTop="125dp"
        android:background="@drawable/shape_register"
        android:gravity="center"
        android:text="@string/label_bind_and_login"
        android:textColor="@color/white"
        android:textSize="16sp"
        android:textStyle="bold" />

</RelativeLayout>`

**Comment by Liberations** [comment]
注释掉CommonTitleBar 即可正常获取焦点，CommonTitleBar中添加如下代码也无效 定位到
`     android:focusable="false"
        android:focusableInTouchMode="false"`

定位到是标题中的跑马灯效果有获取焦点的操作
`tvCenter.setMaxWidth((int) (ScreenUtils.getScreenPixelSize(context)[0] * 3 / 5.0));
            tvCenter.setEllipsize(TextUtils.TruncateAt.MARQUEE);
            tvCenter.setMarqueeRepeatLimit(-1);
            tvCenter.setFocusable(true);
            tvCenter.setFocusableInTouchMode(true);
            tvCenter.requestFocus();
            tvCenter.setSelected(true);`

如何默认关闭跑马灯效果？

**Comment by Liberations** [comment]
暂时解决方式 让需要获取焦点的Edittext  edt.requestFocus()

**Comment by wuhenzhizao** [comment]
已增加一个新属性 centerTextMarquee，默认为true，可以设置为false来避免焦点抢占的问题
