### ISSUE TITLE
代码设置各种type接口？？

### ISSUE THREAD

**Issue by zhupengxiang** [wuhenzhizao/android-titlebar#27]
请问怎么在代码里设置各种type接口？  和CoordinatorLayout一起使用 导致CoordinatorLayout滑动隐藏控件失效   还有能否控制不用沉浸式

**Comment by wuhenzhizao** [comment]
使用请参考README；和CoordinatorLayout的使用，我没有出现过问题，可以自己定位一下，参考
https://github.com/wuhenzhizao/kotlin-adapter
