### ISSUE TITLE
左右为自定义layout的时候无法响应事件

### ISSUE THREAD

**Issue by jiangaifeng** [wuhenzhizao/android-titlebar#3]
我想在右侧自定义一个扫一扫自定义布局，如何响应事件？

**Comment by wuhenzhizao** [comment]
自定义布局的时候，需要自己手动绑定事件监听

**Comment by wuhenzhizao** [comment]
titleBar.getRightCustomView().setOnClickListener()或
titleBar.getRightCustomView().findViewById(子控件id).setOnClickListener
