### ISSUE TITLE
关于布局报错以及在使用了ViewPager+Fragment的Activity中无法监听点击事件的问题

### ISSUE THREAD

**Issue by wzc119** [wuhenzhizao/android-titlebar#30]
不知道是不是AS的版本问题，我用的3.0.1版本，您的titlebar代码都会报错：Turn off custom view rendering sandboxExec access not allowed during rendering (getprop)。不过这并不影响正常使用。
另一个是使用了ViewPager+Fragment的Activity中无法监听点击事件的问题：我测试的手机是android 8.0的小米6手机。主要的布局是这样的:
<com.wuhenzhizao.titlebar.widget.CommonTitleBar />
    <android.support.v4.view.ViewPager/> //这里用的是您的activity_lauch.xml里的代码
<android.support.design.widget.BottomNavigationView/>
如果把titlebar放进每个fragment对应的子布局里的话，可以监听到右边的textview的点击事件，中间的还是会失灵。
以上的只是我的个人所见，感谢您的代码。

**Comment by wuhenzhizao** [comment]
把完整的布局代码贴出来吧

**Comment by wzc119** [comment]
这是activity_main的布局
<?xml version="1.0" encoding="utf-8"?>
<android.support.constraint.ConstraintLayout
    xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    android:layout_width="match_parent"
    android:layout_height="match_parent">
    <com.wuhenzhizao.titlebar.widget.CommonTitleBar
        xmlns:titlebar="http://schemas.android.com/apk/res-auto"
        android:id="@+id/titlebar"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:layout_marginEnd="0dp"
        android:layout_marginStart="0dp"
        titlebar:statusBarMode="light"
        titlebar:centerText="通用标题栏"
        titlebar:centerTextColor="#ffffff"
        titlebar:bottomShadowHeight="0dp"
        titlebar:showBottomLine="false"
        titlebar:centerType="textView"
        titlebar:rightType="textView"
        titlebar:rightText="切换图标颜色"
        titlebar:rightTextColor="#ffffff" />
    <android.support.v4.view.ViewPager
        android:id="@+id/content"
        android:layout_width="match_parent"
        android:layout_height="0dp"
        android:layout_weight="1"/>
<android.support.design.widget.BottomNavigationView
        android:id="@+id/navigation"
        android:layout_width="0dp"
        android:layout_height="wrap_content"
        android:layout_marginEnd="0dp"
        android:layout_marginStart="0dp"
        android:background="@drawable/shape_gradient_bottom"
        app:layout_constraintBottom_toBottomOf="parent"
        app:layout_constraintLeft_toLeftOf="parent"
        app:layout_constraintRight_toRightOf="parent"
        app:menu="@menu/navigation" />
</android.support.constraint.ConstraintLayout>

以及activity的主要代码
public class MainActivity extends AppCompatActivity{
    private ViewPager viewPager;

    private BottomNavigationView.OnNavigationItemSelectedListener mOnNavigationItemSelectedListener
            = new BottomNavigationView.OnNavigationItemSelectedListener() {
        @Override
        public boolean onNavigationItemSelected(@NonNull MenuItem item) {
            switch (item.getItemId()) {
                case R.id.navigation_home:
                    viewPager.setCurrentItem(0);
                    return true;
                case R.id.navigation_dashboard:
                    viewPager.setCurrentItem(1);
                    return true;
                case R.id.navigation_notifications:
                    viewPager.setCurrentItem(2);
                    return true;
            }
            return false;
        }
    };
    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);
        final CommonTitleBar commonTitleBar = findViewById(R.id.titlebar);
        commonTitleBar.setBackgroundResource(R.drawable.shape_gradient);
        commonTitleBar.setListener(new CommonTitleBar.OnTitleBarListener() {
            @Override
            public void onClicked(View v, int action, String extra) {
                if (action == CommonTitleBar.ACTION_CENTER_TEXT) {
                    Toast.makeText(MainActivity.this,"中间TextView被点击",Toast.LENGTH_SHORT).show();
                } else if(action == CommonTitleBar.ACTION_RIGHT_TEXT){
                    Toast.makeText(MainActivity.this,"右边TextView被点击",Toast.LENGTH_SHORT).show();
                }
                // CommonTitleBar.ACTION_LEFT_TEXT;        // 左边TextView被点击
                // CommonTitleBar.ACTION_LEFT_BUTTON;      // 左边ImageBtn被点击
                // CommonTitleBar.ACTION_RIGHT_TEXT;       // 右边TextView被点击
                // CommonTitleBar.ACTION_RIGHT_BUTTON;     // 右边ImageBtn被点击
                // CommonTitleBar.ACTION_SEARCH;           // 搜索框被点击,搜索框不可输入的状态下会被触发
                // CommonTitleBar.ACTION_SEARCH_SUBMIT;    // 搜索框输入状态下,键盘提交触发，此时，extra为输入内容
                // CommonTitleBar.ACTION_SEARCH_VOICE;     // 语音按钮被点击
                // CommonTitleBar.ACTION_SEARCH_DELETE;    // 搜索删除按钮被点击
                // CommonTitleBar.ACTION_CENTER_TEXT;      // 中间文字点击
            }
        });
        initView();
    }
    private void initView(){
        viewPager = findViewById(R.id.content);
        final BottomNavigationView navigation = findViewById(R.id.navigation);
        navigation.setOnNavigationItemSelectedListener(mOnNavigationItemSelectedListener);
        // 第一次启动时选中第0个tab
        setupViewPager(viewPager);
        //ViewPager监听
        viewPager.addOnPageChangeListener(new ViewPager.OnPageChangeListener() {
            @Override
            public void onPageScrolled(int position, float positionOffset, int positionOffsetPixels) {
            }
            @Override
            public void onPageSelected(int position) {
                navigation.getMenu().getItem(position).setChecked(true);
            }

            @Override
            public void onPageScrollStateChanged(int state) {
            }
        });
    }

    private void setupViewPager(ViewPager viewPager) {
        BottomAdapter adapter = new BottomAdapter(getSupportFragmentManager());
        adapter.addFragment(new PhotoFragment());
        adapter.addFragment(new NewsFragment());
        adapter.addFragment(new OwnFragment());
        viewPager.setAdapter(adapter);
    }
}

**Comment by ncguobiao** [comment]
ViewPager+Fragment）在布局Fragment动态获取 titleBar.centerTextView.text,报空（
