### ISSUE TITLE
SmartTabLayout into Center has tab overlapping with right or left customviews

### ISSUE THREAD

**Issue by waleedmakarem** [wuhenzhizao/android-titlebar#33]
Dear Sir, 
Thanks so much for this great library...
When using SmartTablayout into center which have 4 tabs images , and using right customview with 2 buttons , images are overlapping , as per attached screenshot. Do you have any recommendations ?

非常感谢这个伟大的图书馆......
当SmartTablayout使用具有4个选项卡图像的中心，并使用具有2个按钮的右侧自定义视图时，图像重叠，如附加的屏幕截图所示。你有什么建议 ？
![device-2019-01-31-213251](https://user-images.githubusercontent.com/5726428/52082003-560bf800-25a4-11e9-9d4b-4d741a839272.png)

**Comment by wuhenzhizao** [comment]
It's better to talk with ui designer
