### ISSUE TITLE
主线程执行OSUtils.isMiui()会出现ANR

### ISSUE THREAD

**Issue by tdxtxt** [wuhenzhizao/android-titlebar#36]
机型：红米HM1 
版本：android 4.2.1 
问题原因：在OSUtils.getProp()方法中，有io操作，主线程耗时超过5s

**Comment by wuhenzhizao** [comment]
麻烦提供一下日志

**Comment by tdxtxt** [comment]
日志参考意义不大，但我断点调试，确实在主线程执行input.readLine()时就会超时，无法执行

**Comment by tdxtxt** [comment]
这个仅仅出现在红米这一款手机上，其他手机正常
