### ISSUE TITLE
软键盘弹出时会把TitleBar顶上去，和状态栏重合？

### ISSUE THREAD

**Issue by renjiazhuo** [wuhenzhizao/android-titlebar#37]
如下布局，EditText包含在ScrollView中，但弹出软键盘时同样把TitleBar顶上去了？

```xml
<?xml version="1.0" encoding="utf-8"?>
<LinearLayout>
    <com.wuhenzhizao.titlebar.widget.CommonTitleBar/>
    <ScrollView>
            ...
            <EditText>
            ....
    </<ScrollView>
</LinearLayout>
```

**Comment by wuhenzhizao** [comment]
这个和标题栏没关系了，检查你的布局和软键盘参数



发自我的小米手机
在 任嘉卓 <notifications@github.com>，2019年4月4日 下午4:12写道：

如下布局，EditText包含在ScrollView中，但弹出软键盘时同样把TitleBar顶上去了？

<?xml version="1.0" encoding="utf-8"?>

<LinearLayout>

    <com.wuhenzhizao.titlebar.widget.CommonTitleBar/>

    <ScrollView>

            ...

            <EditText>

            ....

    </<ScrollView>

</LinearLayout>

**Comment by wuhenzhizao** [comment]
在最外层布局加一个属性，fitSystemWindow=true
