### ISSUE TITLE
actionbar setcustomview后高度只有一半

### ISSUE THREAD

**Issue by ghhadisi** [wuhenzhizao/android-titlebar#39]
ActionBar mActionBar = getSupportActionBar();
        View actionbarView =getLayoutInflater().inflate(R.layout.title,null);
//        ActionBar.LayoutParams layoutParams =new ActionBar.LayoutParams(ActionBar.LayoutParams.MATCH_PARENT,
//                ActionBar.LayoutParams.MATCH_PARENT);
        ActionBar.LayoutParams layoutParams =new ActionBar.LayoutParams(ActionBar.LayoutParams.MATCH_PARENT,
                ActionBar.LayoutParams.MATCH_PARENT);
        layoutParams.gravity = Gravity.CENTER_HORIZONTAL |Gravity.CENTER_HORIZONTAL;
        mActionBar.setDisplayOptions(ActionBar.DISPLAY_SHOW_CUSTOM);
        mActionBar.setDisplayShowHomeEnabled(false);
        mActionBar.setDisplayShowCustomEnabled(true);
        mActionBar.setDisplayShowTitleEnabled(false);
        mActionBar.setCustomView(actionbarView, layoutParams);
        Toolbar parent =(Toolbar) actionbarView.getParent();
        parent.setContentInsetsAbsolute(0,0);

**Comment by wuhenzhizao** [comment]
你贴的这个东西和TitleBar有什么关系呢，用的自定义ActionBar而已
