### ISSUE TITLE
为什么标题上面会有padding?

### ISSUE THREAD

**Issue by jjxs** [wuhenzhizao/android-titlebar#4]
怎么去掉
![screenshot_20171218-104350](https://user-images.githubusercontent.com/25605545/34087830-9d1ecb98-e3e0-11e7-8fff-9f82bf2aa9a6.png)

**Comment by wuhenzhizao** [comment]
注意看demo的代码

```java
@Override
public void onAttachedToWindow() {
    super.onAttachedToWindow();
    AppUtils.StatusBarLightMode(getWindow());
    AppUtils.transparencyBar(getWindow());
}
```

**Comment by jjxs** [comment]
解决了谢谢啦

**Comment by wuhenzhizao** [comment]
@jjxs ，我看上图右侧的勾图标，离屏幕右侧有点宽，可以修改一下图片宽度，应该是图片水平方向留边有点多了

**Comment by jjxs** [comment]
奇怪,我左右两个图片是一样大小的,

**Comment by wuhenzhizao** [comment]
我中间有个版本调整了边距，左右有差别，统一过来了，请使用最新版 1.0.6

**Comment by jjxs** [comment]
好嘞

**Comment by wuhenzhizao** [comment]
@jjxs ，最近主要是去编写[kotlin-adapter](https://github.com/wuhenzhizao/kotlin-adapter)了，可以关注一下

**Comment by jjxs** [comment]
好的
