### ISSUE TITLE
能否再次封装或者拓展

### ISSUE THREAD

**Issue by thunderning** [wuhenzhizao/android-titlebar#46]
能否将大部分由xml定义的属性开成protected呢？这样在需要大量重复titlebar的时候可以直接继承一个新类而不是复制粘贴大量xml代码，可拓展性更强

**Comment by wuhenzhizao** [comment]
xml中不需要定义所有属性，用到哪个声明哪个。复用xml属性不一定需要继承类实现，style也是一种方式

**Comment by RicardoJiang** [comment]
同建议添加扩展性，自定义centerView的时候，有时宽度需要设置为Match_Parent，同时需要在leftView,rightView两边之间。建议开放属性为protect
