### ISSUE TITLE
请问在Android4.4中如何使用

### ISSUE THREAD

**Issue by zhangchaoxu** [wuhenzhizao/android-titlebar#5]
demo如果在Android4.4中运行，报错`java.lang.IllegalStateException: You need to use a Theme.AppCompat theme (or descendant) with this activity.`

尝试修复：将v19/styles.xml中的AppTheme定义从`parent="android:Theme.Holo.Light.NoActionBar.TranslucentDecor"`改成`parent="AppTheme.Base"`，运行以后发现titlebar直接顶着头部，没有留出statusbar的高度空间。
当然fitsSystemWindows=true以后可以解决这个问题，但是对其他版本又会造成影响。

请问如何处理？

**Comment by zhangchaoxu** [comment]
我觉得CommonTitleBar中对于supportStatusBarLightMode的判断，应该只需要判断版本号>=19就可以

**Comment by wuhenzhizao** [comment]
@zhangchaoxu ，android6.0才真正对沉浸式标题栏支持的比较好，国内第三方rom，比如miui和flymeOs有自己的支持，可以低于6.0，这个地方我需要优化一下；你说的那个闪退是存在的，是demo的问题，写demo的时候，用了滑动返回，有v-19的主题，很久没维护了，我改一下。谢谢你的反馈

**Comment by zhangchaoxu** [comment]
@wuhenzhizao 感谢答复，我觉得这个问题首先是要把statusbar的高度空间留出来，其次再去探讨如何实现对statusbar的染色等操作。

**Comment by zhangchaoxu** [comment]
另外顺便补充一个问题，高度44dp是有什么依据吗，我截图对比了微信等应用，发现44dp还是有点低，应该在56dp左右。
当然，我知道titleBarHeight可以自定义。

**Comment by wuhenzhizao** [comment]
44dp只是我自己设定的，默认值，之前UED用的比较多，没有依据，标题栏高度可以自己配置的

**Comment by wuhenzhizao** [comment]
我建议你把这个类拷出来，自己修改默认值，不是很推荐用aar依赖

**Comment by wuhenzhizao** [comment]
@zhangchaoxu ，闪退的问题解决了，demo那块的问题，不需要修改CommonTitleBar，可以重新下载

**Comment by wuhenzhizao** [comment]
有问题加群，见README
