### ISSUE TITLE
为啥设置elevation不生效,我拿你的demo测试的

### ISSUE THREAD

**Issue by meijingkang** [wuhenzhizao/android-titlebar#6]

**Comment by wuhenzhizao** [comment]
你好，最早的时候elevation是生效的，后面考虑到效果不是太好，中间某个版本去掉了，有部分说明未移除。最新的版本中，我加了一个选项，设置底部阴影高度，bottomShadowHeight，使用该属性时，需要显式声明 showBottomLine = false
