### ISSUE TITLE
titbar的背景设置成一张渐变的背景图

### ISSUE THREAD

**Issue by darkSuperman** [wuhenzhizao/android-titlebar#8]
作者你好，你这titbar背景只能给颜色值，如何扩展可以给一张渐变背景图或者渐变shape成为背景，有什么方便快速的建议吗？谢谢

**Comment by darkSuperman** [comment]
rlMain = new RelativeLayout(context);
        rlMain.setId(AppUtils.generateViewId());
        rlMain.setBackgroundColor(titleBarColor);
我可以直接用反射把setBackgroundColor(）换成setBackgroundResource(),这样可以吗

**Comment by wuhenzhizao** [comment]
你可以直接给整个TitleBar设置背景图，不需要反射
