### ISSUE TITLE
部分机型号，屏幕始终填充不满

### ISSUE THREAD

**Issue by darkSuperman** [wuhenzhizao/android-titlebar#9]
作者你好，使用你这个titbar后屏幕底部始终有个白底，白底的高度就是状态栏的高度。
目前魅蓝 m3，金立m6上会出现这个问题。系统版本都是5.0的，请提示下处理思路。

**Comment by wuhenzhizao** [comment]
请提供截图

**Comment by darkSuperman** [comment]
![1](https://user-images.githubusercontent.com/23699296/38194038-c330e964-36a7-11e8-9e14-2a09458a5ccd.jpg)

**Comment by darkSuperman** [comment]
我目前的做法只是获取这两个手机型号，获取状态栏高度，然后给最外层布局layoutParams.setMargins(0, 0, 0, -statusBarHeight);虽然有效，但是很多界面有bar，很多界面就要处理，很头疼。而且怕别的未知机型也会出现这个问题。希望能够在titbar里面 入手

**Comment by darkSuperman** [comment]
我目前的做法只是获取这两个手机型号，获取状态栏高度，然后给最外层布局layoutParams.setMargins(0, 0, 0, -statusBarHeight);虽然有效，但是很多界面有bar，很多界面就要处理，很头疼。而且怕别的未知机型也会出现这个问题。希望能够在titbar里面 入手

**Comment by wuhenzhizao** [comment]
![image](https://user-images.githubusercontent.com/10915591/38194107-1ac831aa-36a8-11e8-89ab-f6379539f289.png)
尝试注掉倒数第一行或倒数第二行试试，这个可能和沉浸式有关

**Comment by darkSuperman** [comment]
嗯，走来想到过，注释过了，无效。

**Comment by wuhenzhizao** [comment]
请加qq群联系，群号:98911449

**Comment by wuhenzhizao** [comment]
未使用控件的情况下如此，系统rom问题
